<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net10.0</TargetFrameworks>
        <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
        <ApplicationIcon />
        <OutputType>Library</OutputType>
        <StartupObject />
        <NuspecFile>Transmission.API.RPC.nuspec</NuspecFile>
        <PackageIcon>https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Transmission_Icon.svg/2000px-Transmission_Icon.svg.png</PackageIcon>
    </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|netstandard2.0|AnyCPU'">
    <DocumentationFile>D:\Workspace\Github\Transmission.API.RPC\Transmission.API.RPC\bin\Debug\netstandard2.0\Transmission.API.RPC.xml</DocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|netstandard2.0|AnyCPU'">
    <DocumentationFile>D:\Workspace\Github\Transmission.API.RPC\Transmission.API.RPC\bin\Release\netstandard2.0\Transmission.API.RPC.xml</DocumentationFile>
  </PropertyGroup>

</Project>
